#! /usr/bin/python
import sys
import os.path
from ilcsoft import *

if( len(sys.argv) < 2 or len(sys.argv) >3 ):
    # display usage information
    print "\n Usage: " + sys.argv[0] + " [-s, -p, -i] \"install.cfg\"\n"
    print "   -s to display installation summary"
    print "   -p to preview installation "
    print "   -i to install the software "
    print
    sys.exit(1)

else:
    valid_options = ['s','p','i']
    if( len(sys.argv) == 2 ):
        option = 's'

    # get the config file from the option's list
    for opt in sys.argv:

        if( (opt != sys.argv[0]) and (opt[0] != "-") ):
            config_file = opt
            break
    else:
        print "you need to specify a config file!!"
        sys.exit(1)
    
    if( not os.path.exists(config_file) ):
        print "you need to specify a valid config file!!"
        sys.exit(1)
    
    # get the option to be executed
    for opt in sys.argv:
        
        if( opt[0] == "-" ):
            if( len(opt) > 2 ):
                print "invalid option:",opt
                sys.exit(1)
            else:
                option=opt[1:]
    
    print "\n" + 30*'*' + " Starting installation process... " + 30*'*' + "\n"

    print "+ Read configuration file [ " + config_file + " ]\n"
    # read configuration file
    execfile( config_file )

    # pass the name of the config file to ilcsoft
    ilcsoft.config_file = config_file
    ilcsoft.config_file_prefix = config_file[config_file.rfind( '/' )+1:config_file.rfind(".")]
    ilcsoft.config_file_suffix = config_file[config_file.rfind(".")+1:]

    # this is for initializing the modules
    # (called right after reading the config file)
    ilcsoft.init()

    if( option == "s" ):
        # display installation summary
        ilcsoft.summary()
    elif( option == "p" ):
        # test install
        ilcsoft.previewinstall()
    elif( option == "i" ):
        # install software
        ilcsoft.makeinstall()

    print "\n" + 30*'*' + " Finished installation process... " + 30*'*' + "\n"

