FROM centos:centos7

LABEL product="iLCSoft"
LABEL maintainer="remi.ete@desy.de"
LABEL description="Image setting up the OS flavor, compiler version \
and any other environement for building iLCSoft 'base' and 'ilcsoft' stacks"
LABEL os="centos 7"
LABEL compiler="GCC 8.2.1"
LABEL python="Python 2.7.15"

# Perform the installation as root:
USER root
ENV HOME /home/ilc
ENV ILCSOFT /home/ilc/ilcsoft

RUN yum -y update && \
    yum install -y \
      curl \
      tar \
      bzip2 \
      wget \
      tar \
      git \
      which \
      make \
      libX11-devel \
      libXext-devel \
      freeglut-devel \
      libXmu-devel \
      libXpm-devel \
      libXft-devel \
      python-devel \
      subversion \
      doxygen \
      texlive \
      mysql \
      mysql-devel \
      emacs \
      ghostscript \
      texlive-xetex \
      texlive-xetex-def \
      texlive-collection-xetex \
      texlive-xtab \
      texlive-tocloft \
      texlive-sectsty \
      texlive-multirow
        
RUN yum clean all

RUN yum install -y centos-release-scl  
RUN yum install -y devtoolset-8-gcc-c++ 

SHELL [ "/usr/bin/scl", "enable", "devtoolset-8"]

WORKDIR ${HOME}

# Install Python 2.7, compiled against the GCC version we use here (very important !)
RUN wget http://lcgpackages.web.cern.ch/lcgpackages/tarFiles/sources/Python-2.7.15.tgz && \
    tar xvf Python-2.7.15.tgz && \
    cd Python-2.7.15 && \
    ./configure --prefix=$HOME/python --enable-ipv6 --enable-shared --enable-unicode=ucs4 CXX=/opt/rh/devtoolset-8/root/bin/g++ CC=/opt/rh/devtoolset-8/root/bin/gcc && \
    make install -j 10 && \
    cd $HOME && \
    rm -rf Python-2.7.15 Python-2.7.15.tgz

ENV PATH ${HOME}/python/bin:${PATH}
ENV LD_LIBRARY_PATH ${HOME}/python/lib:${LD_LIBRARY_PATH}

# Start the image with BASH by default
CMD ["/bin/bash"]